### ISSUE TITLE
on version 2.0.1 ReactRating-component onChange-event seems to return always value of initialRating

### ISSUE THREAD

**Issue by bumpah** [dreyescat/react-rating#136] opened 2019-11-26 12:41 UTC
Following occurs,

v2.0.1 => value in onChange-event is always same as initialRating-value [https://codesandbox.io/s/react-rating-201-9p75n](https://codesandbox.io/s/react-rating-201-9p75n)
v2.0.0 => works as expected [https://codesandbox.io/s/react-rating-200-pm4n9](https://codesandbox.io/s/react-rating-200-pm4n9)

example behavior in CodeSandbox

**Comment by dreyescat** [comment] 2019-11-26 13:56
Thanks @bumpah for the sandboxes! That really helps to track down the issue.

Something weird is happening... If you change the [react version down to 16.3 it works](https://codesandbox.io/s/react-rating-201-e7by3). From react version 16.4 upwards then the behavior is what you describe.

**Comment by dreyescat** [comment] 2019-11-26 14:23
[React 16.4 Bugfix for getDerivedStateFromProps](https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops) might be the reason why it is working in React 16.3 and not from 16.4 and above.

Too look into: 

- [You Probably Don't Need Derived State](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html)

**Comment by bumpah** [comment] 2019-11-26 16:31
I believe here is a cultrip on `this.props.onChange`-call
 ```
 handleClick(value, e) {
    const newValue = this.translateDisplayValueToValue(value);
    this.props.onClick(newValue);
    // Avoid calling setState if not necessary. Micro optimisation.
    if (this.state.value !== newValue) {
      // If we have a new value trigger onChange callback.
      this.setState({
        value: newValue
      }, () => this.props.onChange(this.state.value)); // this.state.value is here 
    }
  }
```
Inspected this a little bit and you'll notice that `this.state.value` does not get updated as expected and always provides value of a initialRating -value (initial state so to say).

**Comment by dreyescat** [comment] 2019-11-26 16:57
Yep. I have just taken a quick look and yes. It is because the `getDerivedStateFromProps` is called before the `setState` callback. There, in the `getDerivedStateFromProps`,  the `state.value` is set to `initialRating` because, yes, the `initialRating` is *likely* to be different than the recently clicked/set `value`. So, basically, we are always setting `initialRating` as the current value 😓.

```javascript
  static getDerivedStateFromProps(props, prevState) {
    const { initialRating } = props;
    return (initialRating !== prevState.value)
      ? { value: initialRating }
      : null;
  }
```

Roughly this is the sequence of calls:

1. handleClick
1. getDerivedStateFromProps
1. setState callback

In the meantime a solution is found I have deprecated the 2.0.1 version.
I have published the version 2.0.2 that is just a copy of the 2.0.0 to try to cut the bleeding 😉.

**Comment by bumpah** [comment] 2019-11-26 17:08
What is the main objective you want to achieve by using `getDerivedStateFromProps`-function to set initialRating this way?

If you remove that function, component works as I would describe "as you'll expect".

if you want only set `initialRating` once when component mounts that is already handled by in component constructor function,
```
    this.state = {
      value: props.initialRating
    };
```

If you which to achieve something more complex with this that im not currently aware I can collaborate with this issue if given some details.

**Comment by dreyescat** [comment] 2019-11-27 17:58
> What is the main objective you want to achieve by using getDerivedStateFromProps-function to set initialRating this way?

It is a long story :wink:. In short, it is an attempt to replace/get rid of the deprecated `componentWillReceiveProps` while keeping the same controlled/uncontrolled component behavior.
 
In #129 we just tried to replace this deprecated life cycle method with the, I thought *equivalent*, `getDerivedStateFromProps` method. But, as you can see they are not actually equivalent.

After discussing this replacement in PR #129 with @tstirrat15 and reading [You Probably Don't Need Derived State](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) and [Always be ready to render](https://overreacted.io/writing-resilient-components/#principle-2-always-be-ready-to-render) posts, we agreed that trying to keep this double behavior (controlled and uncontrolled) brings an unnecessary complexity.

A new issue #134 was created with the goal of refactoring it to meet the currently recommended [best practice](https://reactjs.org/docs/forms.html#controlled-components).

Hope it gives you some context.

And of course, I would be really glad of any kind of collaboration 😃

**Comment by dreyescat** [comment] 2019-11-27 22:37
Forgot to actually revert the offending code 😞. The good reverted version is 2.0.3. Apologies.

**Comment by zehawki** [comment] 2020-09-24 09:52
After wrangling with this for quite a while, I finally concluded that this must be a bug in react-rating and then a search brought me here. I'm on v2.0.5, so I'm a bit confused whether this is still an issue or sorted in 2.0.3?

**Comment by dreyescat** [comment] 2020-09-24 11:03
@zehawki Yep. It should have been fixed on **v2.0.3 or greater**. The affected versions should only be *v2.0.1* and *v2.0.2*. So *v2.0.5* should be fine. Sorry for the confusion it could have caused.

**Comment by zehawki** [comment] 2020-09-25 11:51
Well the reason I posted is that I see the issue is there in 2.0.5...

**Comment by dreyescat** [comment] 2020-09-25 14:18
Then it should be another reason causing the *same* issue.

I just forked the offending version from the OP:
v2.0.1 => value in `onChange` event is always same as `initialRating` value https://codesandbox.io/s/react-rating-201-9p75n

with the version you say:
v2.0.5 => value in `onChange` event is as expected https://codesandbox.io/s/react-rating-205-te4ik

and it seems fixed. I mean, the value is changed.

Could you use a fork of this codesandox and try to reproduce your issue?

**Comment by zehawki** [comment] 2020-09-25 15:44
Please see this starting point: https://codesandbox.io/s/react-rating-205-forked-n5wps?file=/src/index.js. As soon as there is a real onchange handler, things behave strangely. In this case, it takes 2 clicks to register.

Next: https://codesandbox.io/s/react-rating-205-forked-ffkzz?file=/src/index.js: 1st click resets to initial rating and 2nd click registers the new rating.

**Comment by dreyescat** [comment] 2020-09-25 16:40
I think I know what's the problem... It is the evil `initialRating` name hitting again :sweat:.

When you are handling the state yourself (like `useState` does), then `initialRating` becomes the actual value. I know. The name is misleading and is one of the things we should improve in next versions. 

You have to provide the `value` otherwise the rating will get stuck with the `initiaRating`. Actually, this, the uncontrolled way, is the way this component should aim to and get rid of the confusing *controlled* one.

```javascript
function App() {
  const [value, setValue] = useState(11);

  useEffect(() => {
    console.log(value);
  });

  return (
    <div className="App">
      <ReactRating
        start={6}
        stop={16}
        initialRating={value}
        onChange={setValue}
      />
    </div>
  );
}
```
Check https://codesandbox.io/s/react-rating-205-forked-qcz09

For more information:

Sometimes initialRating property name leads to confusion. It is not the first time having problems with such a name (#84 or #108). It is used as the initial value for the uncontrolled version and the value for the controlled version. I mean, when used as an uncontrolled component the state value is initialized to the initialRating, but, when it is used as a controlled component the state value matches to the **initialRating.**

**Comment by dreyescat** [comment] 2020-09-25 16:44
I close this issue because new versions (>= v2.0.3) solve the original bug.

**Closed by dreyescat** 2020-09-25 16:44 UTC
Labels: bug

**Comment by zehawki** [comment] 2020-09-25 17:10
I feel there's a fair amount of misunderstanding of React going on here. Whether the component is controlled or uncontrolled, it still has to send its value to the outside world else whats the point. The only way it will send its value outside is via an onClick or onChange. And therefore, there is no condition in which one would not use an onChange. And merely because onChange is called, it does NOT mean that: _When you are handling the state yourself (like useState does), then initialRating becomes the actual value. I know_

Put differently: just because onChange is called, does not mean that the state of this component is being handed from outside, ie controlled. It would be controlled if a props like "value" was send back into this component and actually used. You would see in the code that I've provided, I'm using this component in uncontrolled mode.

Now to correctly get uncontrolled mode working, with an initialValue, all you have to do is this:

1. Get rid of both UNSAFE_componentWillReceiveProps functions. These are not needed.
2. In componentDidUpdate of class Rating, add:     

```
if (this.props.value !== prevProps.value)
      this.setState({ displayValue: this.props.value })
```
initialRating is just fine, and will continue to work as its intended, ie starting value
