### ISSUE TITLE
Hover color not working properly when cursor is right between icons

### ISSUE THREAD

**Issue by claradaia** [dreyescat/react-rating#36] opened 2016-12-21 12:11 UTC
When rating, if I place the cursor right between, say, 4th and 5th stars, both will be empty while the first 3 are full, same for 3rd and 4th start with first 2 etc. It's a very small problem, but makes the rating look buggy. I'm using material design icons, but it also happens with the default icon. Looks like there's some sort of border around the icons, but it does not show when inspecting the elements. Any advice?

**Comment by dreyescat** [comment] 2016-12-21 18:32
I tried on Firefox and Edge and I could not reproduce the issue. But Chrome seems to show this weird behaviour. Do you have access to other browsers? Could you check if it is only a Chrome specific bug?

**Comment by dreyescat** [comment] 2016-12-21 18:35
I bet it is some CSS specific weird issue 😒

**Comment by dreyescat** [comment] 2016-12-22 19:54
@claradaia I think it is a Chrome bug. If you are on a 64-bit OS and you are using the current 32-bit version `55.0.2883.87 m` try to upgrade to the 64-bit version. Just install it again and make sure that the new version is the `55.0.2883.87 m (64-bit)` (mind the 64-bit within parenthesis). I don't know why and how are 32-bit and 64-bit different or if it is the combination of using a 32-bit version on a 64-bit OS... Who knows :wink:.

I am going to close it for now. Let me know if it didn't work for you.

**Comment by dreyescat** [comment] 2017-01-06 10:06
I was wrong. It also happens in the 64-bit version of Chrome. It only happens to me between odd and even symbols. That is, between the first and the second, the third and the fourth symbol, and so on. I have tried with Firefox and Internet Explorer and it works as expected. This is weird.

**Comment by ImanMh** [comment] 2017-05-22 10:41
It can be fixed by adding a CSS delay, I have the same issue

**Comment by dreyescat** [comment] 2018-02-10 09:57
This issue should be solved since v1. I close this issue as we are not solving for good old version v0.
If anyone face this issue on v1 then we will re-open this issue.

**Closed by dreyescat** 2018-02-10 09:57 UTC
Labels: bug, help wanted
